/**
 * Role-to-Permissions mapping
 * Defines what permissions each role has
 * This is the central source of truth for RBAC
 */

import { PERMISSIONS } from "./permissions.js";

export const ROLE_PERMISSIONS = {
  SUPER_ADMIN: [
    // Everything - Super Admin has all permissions
    Object.values(PERMISSIONS),
  ].flat(),

  ADMIN: [
    // Admin has all operational permissions within a hotel
    Object.values(PERMISSIONS),
  ].flat(),

  MANAGER: [
    // Manager - operations, inventory, recipes, reports, workforce management
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.ANALYTICS_VIEW,

    // Inventory
    PERMISSIONS.INVENTORY_VIEW,
    PERMISSIONS.INVENTORY_CREATE,
    PERMISSIONS.INVENTORY_UPDATE,
    PERMISSIONS.INVENTORY_DELETE,
    PERMISSIONS.INVENTORY_TRANSACTIONS_VIEW,
    PERMISSIONS.INVENTORY_TRANSACTIONS_CREATE,
    PERMISSIONS.INVENTORY_TRANSACTIONS_DELETE,
    PERMISSIONS.STOCK_COUNTS_VIEW,
    PERMISSIONS.STOCK_COUNTS_CREATE,
    PERMISSIONS.STOCK_COUNTS_UPDATE,
    PERMISSIONS.STOCK_COUNTS_DELETE,
    PERMISSIONS.LOW_STOCK_VIEW,

    // Recipes
    PERMISSIONS.RECIPES_VIEW,
    PERMISSIONS.RECIPES_CREATE,
    PERMISSIONS.RECIPES_UPDATE,
    PERMISSIONS.RECIPES_DELETE,
    PERMISSIONS.RECIPES_RECALCULATE,
    PERMISSIONS.RECIPE_INGREDIENTS_VIEW,
    PERMISSIONS.RECIPE_INGREDIENTS_CREATE,
    PERMISSIONS.RECIPE_INGREDIENTS_UPDATE,
    PERMISSIONS.RECIPE_INGREDIENTS_DELETE,

    // Food Cost & Analytics
    PERMISSIONS.FOOD_COST_VIEW,
    PERMISSIONS.INVENTORY_CONSUMPTION_VIEW,
    PERMISSIONS.INVENTORY_CONSUMPTION_CREATE,
    PERMISSIONS.INVENTORY_CONSUMPTION_UPDATE,
    PERMISSIONS.WASTE_VIEW,
    PERMISSIONS.WASTE_CREATE,
    PERMISSIONS.WASTE_UPDATE,
    PERMISSIONS.WASTE_DELETE,
    PERMISSIONS.LEAKAGE_VIEW,
    PERMISSIONS.PROFITABILITY_VIEW,
    PERMISSIONS.REPORTS_VIEW,

    // Purchases & Suppliers
    PERMISSIONS.PURCHASES_VIEW,
    PERMISSIONS.PURCHASES_CREATE,
    PERMISSIONS.PURCHASES_UPDATE,
    PERMISSIONS.PURCHASES_DELETE,
    PERMISSIONS.PURCHASES_STATUS_CHANGE,
    PERMISSIONS.SUPPLIERS_VIEW,
    PERMISSIONS.SUPPLIERS_CREATE,
    PERMISSIONS.SUPPLIERS_UPDATE,
    PERMISSIONS.SUPPLIERS_DELETE,

    // Workforce
    PERMISSIONS.EMPLOYEES_VIEW,
    PERMISSIONS.EMPLOYEES_CREATE,
    PERMISSIONS.EMPLOYEES_UPDATE,
    PERMISSIONS.EMPLOYEES_DELETE,
    PERMISSIONS.ATTENDANCE_VIEW,
    PERMISSIONS.ATTENDANCE_MANAGE,
    PERMISSIONS.SCHEDULES_VIEW,
    PERMISSIONS.SCHEDULES_CREATE,
    PERMISSIONS.SCHEDULES_UPDATE,
    PERMISSIONS.SCHEDULES_DELETE,
    PERMISSIONS.WORKFORCE_REPORTS_VIEW,

    // Room Operations
    PERMISSIONS.ROOMS_VIEW,
    PERMISSIONS.ROOMS_MANAGE,
    PERMISSIONS.RESERVATIONS_VIEW,
    PERMISSIONS.RESERVATIONS_CREATE,
    PERMISSIONS.RESERVATIONS_UPDATE,
    PERMISSIONS.RESERVATIONS_DELETE,
    PERMISSIONS.HOUSEKEEPING_VIEW,
    PERMISSIONS.HOUSEKEEPING_ASSIGN,
    PERMISSIONS.HOUSEKEEPING_UPDATE,
    PERMISSIONS.LATE_CHECKOUT_VIEW,
    PERMISSIONS.LATE_CHECKOUT_MANAGE,

    // POS
    PERMISSIONS.POS_VIEW,
    PERMISSIONS.POS_CREATE,
    PERMISSIONS.POS_TRANSACTIONS,
    PERMISSIONS.ORDERS_VIEW,
    PERMISSIONS.ORDERS_CREATE,
    PERMISSIONS.ORDERS_UPDATE,
    PERMISSIONS.ORDERS_DELETE,
    PERMISSIONS.KITCHEN_DISPLAY_VIEW,

    PERMISSIONS.MEASUREMENT_UNITS_VIEW,
    PERMISSIONS.NOTIFICATIONS_VIEW,
    PERMISSIONS.SETTINGS_VIEW,
  ],

  RECEPTION: [
    // Dashboard & System
    // PERMISSIONS.DASHBOARD_VIEW,
    // PERMISSIONS.NOTIFICATIONS_VIEW,

    // Room Operations & Guest Management
    PERMISSIONS.ROOMS_VIEW,
    PERMISSIONS.ROOMS_MANAGE,
    PERMISSIONS.RESERVATIONS_VIEW,
    PERMISSIONS.RESERVATIONS_CREATE,
    PERMISSIONS.RESERVATIONS_UPDATE,
    PERMISSIONS.RESERVATIONS_DELETE,
    PERMISSIONS.LATE_CHECKOUT_VIEW,
    PERMISSIONS.LATE_CHECKOUT_MANAGE,

    // Housekeeping (Fixes the missing pages/reports)
    PERMISSIONS.HOUSEKEEPING_VIEW,
    PERMISSIONS.HOUSEKEEPING_ASSIGN,
    PERMISSIONS.HOUSEKEEPING_UPDATE,

    // POS, Orders & Basic Inventory
    // PERMISSIONS.INVENTORY_VIEW, // Read-only view
    // PERMISSIONS.ORDERS_VIEW,
    // PERMISSIONS.ORDERS_CREATE,

    // Workforce & Attendance
    PERMISSIONS.EMPLOYEES_VIEW,
    PERMISSIONS.EMPLOYEES_CREATE,
    PERMISSIONS.EMPLOYEES_UPDATE,
    PERMISSIONS.EMPLOYEES_DELETE,
    PERMISSIONS.ATTENDANCE_VIEW,
    PERMISSIONS.ATTENDANCE_MANAGE,
    PERMISSIONS.SCHEDULES_VIEW,
    PERMISSIONS.SCHEDULES_CREATE,
    PERMISSIONS.SCHEDULES_UPDATE,
    PERMISSIONS.SCHEDULES_DELETE,
    PERMISSIONS.WORKFORCE_REPORTS_VIEW,
  ],
  CASHIER: [
    // Cashier - POS, payments, order transactions
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.NOTIFICATIONS_VIEW,
    PERMISSIONS.POS_VIEW,
    PERMISSIONS.POS_CREATE,
    PERMISSIONS.POS_TRANSACTIONS,
    PERMISSIONS.ORDERS_VIEW,
    PERMISSIONS.ORDERS_CREATE,
    PERMISSIONS.ORDERS_UPDATE,
    PERMISSIONS.KITCHEN_DISPLAY_VIEW,
    PERMISSIONS.INVENTORY_VIEW, // Read-only for stock info
  ],

  CHEF: [
    // Chef - kitchen, recipes, inventory viewing for recipe ingredients
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.NOTIFICATIONS_VIEW,
    PERMISSIONS.RECIPES_VIEW,
    PERMISSIONS.RECIPE_INGREDIENTS_VIEW,
    PERMISSIONS.INVENTORY_VIEW, // Read-only
    PERMISSIONS.KITCHEN_DISPLAY_VIEW,
    PERMISSIONS.FOOD_COST_VIEW,
    PERMISSIONS.INVENTORY_CONSUMPTION_VIEW,
    PERMISSIONS.WASTE_VIEW,
  ],

  CLEANER: [
    // Cleaner - housekeeping tasks only
    PERMISSIONS.HOUSEKEEPING_VIEW,
    PERMISSIONS.HOUSEKEEPING_UPDATE,
    PERMISSIONS.ROOMS_VIEW,
    PERMISSIONS.NOTIFICATIONS_VIEW,
  ],

  VIEWER: [
    // Viewer - read-only access to dashboards and reports
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.ANALYTICS_VIEW,
    PERMISSIONS.NOTIFICATIONS_VIEW,
    PERMISSIONS.INVENTORY_VIEW,
    PERMISSIONS.RECIPES_VIEW,
    PERMISSIONS.FOOD_COST_VIEW,
    PERMISSIONS.INVENTORY_CONSUMPTION_VIEW,
    PERMISSIONS.WASTE_VIEW,
    PERMISSIONS.LEAKAGE_VIEW,
    PERMISSIONS.PROFITABILITY_VIEW,
    PERMISSIONS.REPORTS_VIEW,
    PERMISSIONS.PURCHASES_VIEW,
    PERMISSIONS.SUPPLIERS_VIEW,
    PERMISSIONS.WORKFORCE_REPORTS_VIEW,
    PERMISSIONS.ROOMS_VIEW,
    PERMISSIONS.RESERVATIONS_VIEW,
    PERMISSIONS.ORDERS_VIEW,
  ],
};

export default ROLE_PERMISSIONS;
