module.exports = {
  content: [
    "./App.{js,jsx}",
    "./app/**/*.{js,jsx}",
    "./components/**/*.{js,jsx}",
  ],
  presets: [require("nativewind/preset")],
  theme: {
    extend: {
      fontFamily: {
        regular: ["Poppins-Regular"],
        medium: ["Poppins-Medium"],
        semibold: ["Poppins-SemiBold"],
        bold: ["Poppins-Bold"],
      },
      colors: {
        "tertiary-fixed": "#ffd9e3",
        "on-surface-variant": "#494551",
        "on-tertiary-fixed": "#31111d",
        "surface-tint": "#6750a4",
        "primary-fixed": "#e9ddff",
        "on-primary": "#ffffff",
        "secondary-container": "#e8def9",
        primary: "#4f378a",
        "surface-container-high": "#ebe7ec",
        "on-tertiary-fixed-variant": "#633b48",
        "surface-bright": "#fdf8fd",
        background: "#fdf8fd",
        "error-container": "#ffdad6",
        "tertiary-container": "#7d5260",
        tertiary: "#633b48",
        "inverse-surface": "#313034",
        "surface-container": "#f1ecf2",
        "on-secondary-fixed": "#1e192b",
        "surface-container-highest": "#e5e1e7",
        "on-surface": "#1c1b1f",
        "on-error-container": "#93000a",
        "surface-container-lowest": "#ffffff",
        secondary: "#625b71",
        "outline-variant": "#cbc4d2",
        "surface-dim": "#ddd9de",
        "on-primary-fixed": "#22005d",
        outline: "#7a7582",
        "on-tertiary": "#ffffff",
        error: "#ba1a1a",
        "on-background": "#1c1b1f",
        "on-secondary": "#ffffff",
        "secondary-fixed-dim": "#ccc2dc",
        "primary-fixed-dim": "#cfbcff",
        surface: "#fdf8fd",
        "inverse-primary": "#cfbcff",
        "secondary-fixed": "#e8def9",
        "tertiary-fixed-dim": "#eeb8c8",
        "on-error": "#ffffff",
        "on-secondary-container": "#686177",
        "primary-container": "#6750a4",
        "on-tertiary-container": "#ffcbda",
        "inverse-on-surface": "#f4eff5",
        "on-primary-fixed-variant": "#4f378a",
        "on-secondary-fixed-variant": "#4a4358",
        "surface-container-low": "#f7f2f8",
        "on-primary-container": "#e0d2ff",
        "surface-variant": "#e5e1e7",
      },
    },
  },
  plugins: [],
};
